require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrderTypesController do

  # This should return the minimal set of attributes required to create a valid
  # OrderType. As you add validations to OrderType, be sure to
  # update the return value of this method accordingly.

  before :each do
    @order_type = Factory :order_type
  end

  describe "GET index" do
    it "assigns all order_types as @order_types" do
      order_type = OrderType.create! Factory.attributes_for(:order_type)
      get :index
      assigns(:order_types).should have_at_least(2).items
    end
  end

  describe "GET show" do
    it "assigns the requested order_type as @order_type" do
      order_type = OrderType.create! Factory.attributes_for(:order_type)
      get :show, :id => order_type.id
      assigns(:order_type).should eq(order_type)
    end
  end

  describe "GET new" do
    it "assigns a new order_type as @order_type" do
      get :new
      assigns(:order_type).should be_a_new(OrderType)
    end
  end

  describe "GET edit" do
    it "assigns the requested order_type as @order_type" do
      order_type = OrderType.create! Factory.attributes_for(:order_type)
      get :edit, :id => order_type.id
      assigns(:order_type).should eq(order_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OrderType" do
        expect {
          post :create, :order_type => Factory.attributes_for(:order_type)
        }.to change(OrderType, :count).by(1)
      end

      it "assigns a newly created order_type as @order_type" do
        post :create, :order_type => Factory.attributes_for(:order_type)
        assigns(:order_type).should be_a(OrderType)
        assigns(:order_type).should be_persisted
      end

      it "redirects to the created order_type" do
        post :create, :order_type => Factory.attributes_for(:order_type)
        response.should redirect_to(OrderType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved order_type as @order_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrderType.any_instance.stub(:save).and_return(false)
        post :create, :order_type => {}
        assigns(:order_type).should be_a_new(OrderType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrderType.any_instance.stub(:save).and_return(false)
        post :create, :order_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested order_type" do
        order_type = OrderType.create! Factory.attributes_for(:order_type)
        # Assuming there are no other order_types in the database, this
        # specifies that the OrderType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OrderType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => order_type.id, :order_type => {'these' => 'params'}
      end

      it "assigns the requested order_type as @order_type" do
        order_type = OrderType.create! Factory.attributes_for(:order_type)
        put :update, :id => order_type.id, :order_type => Factory.attributes_for(:order_type)
        assigns(:order_type).should eq(order_type)
      end

      it "redirects to the order_type" do
        order_type = OrderType.create! Factory.attributes_for(:order_type)
        put :update, :id => order_type.id, :order_type => Factory.attributes_for(:order_type)
        response.should redirect_to(order_type)
      end
    end

    describe "with invalid params" do
      it "assigns the order_type as @order_type" do
        order_type = OrderType.create! Factory.attributes_for(:order_type)
        # Trigger the behavior that occurs when invalid params are submitted
        OrderType.any_instance.stub(:save).and_return(false)
        put :update, :id => order_type.id, :order_type => {}
        assigns(:order_type).should eq(order_type)
      end

      it "re-renders the 'edit' template" do
        order_type = OrderType.create! Factory.attributes_for(:order_type)
        # Trigger the behavior that occurs when invalid params are submitted
        OrderType.any_instance.stub(:save).and_return(false)
        put :update, :id => order_type.id, :order_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested order_type" do
      order_type = OrderType.create! Factory.attributes_for(:order_type)
      expect {
        delete :destroy, :id => order_type.id
      }.to change(OrderType, :count).by(-1)
    end

    it "redirects to the order_types list" do
      order_type = OrderType.create! Factory.attributes_for(:order_type)
      delete :destroy, :id => order_type.id
      response.should redirect_to(order_types_url)
    end
  end

end
